services :
  django_project :
    build : .
    volumes :
      - .:/app
    working_dir : /app
    command : python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
volumes:
  db_data:
